name: Deploy
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: [antec]
    steps:
      - name: Deploy to antec
        run: |
          cd /home/mikey/pcs
          git pull
          docker compose -p pcs up -d --build
